export const MENUS = [
  {
    fixedColumns: 0,
    hiddenFlag: false,
    pagination: false,
    name: 'System',
    rank: 10000,
    menuType: 'MENU',
    category: 'STANDARD',
    childrens: [
      {
        template: 'things-base-terminology',
        idField: 'name',
        fixedColumns: 0,
        hiddenFlag: false,
        pagination: true,
        titleField: 'name',
        description: 'Base.view.terminology.Terminology',
        itemsProp: 'items',
        resourceName: 'Terminology',
        routing: 'terminologies',
        totalProp: 'total',
        resourceUrl: 'terminologies',
        gridSaveUrl: 'terminologies/update_multiple',
        routingType: 'STATIC',
        name: 'Terminology',
        rank: 800,
        menuType: 'SCREEN',
        category: 'STANDARD',
        resourceType: 'ENTITY'
      },
      {
        template: 'things-base-menu',
        idField: 'name',
        fixedColumns: 3,
        hiddenFlag: false,
        pagination: true,
        detailFormId: 'things-base-menu-setup',
        titleField: 'name',
        itemsProp: 'items',
        resourceName: 'Menu',
        routing: 'menus',
        totalProp: 'total',
        resourceUrl: 'menus',
        gridSaveUrl: 'menus/update_multiple',
        routingType: 'STATIC',
        name: 'Menu',
        rank: 700,
        menuType: 'SCREEN',
        category: 'STANDARD',
        resourceType: 'ENTITY'
      },
      {
        idField: 'name',
        fixedColumns: 0,
        hiddenFlag: false,
        pagination: true,
        detailFormId: 'things-resource-form',
        titleField: 'name',
        itemsProp: 'items',
        resourceName: 'Setting',
        routing: 'settings',
        totalProp: 'total',
        resourceUrl: 'settings',
        gridSaveUrl: 'settings/update_multiple',
        routingType: 'RESOURCE',
        name: 'Setting',
        rank: 500,
        menuType: 'SCREEN',
        category: 'STANDARD',
        resourceType: 'ENTITY'
      },
      {
        idField: 'name',
        fixedColumns: 0,
        hiddenFlag: false,
        pagination: true,
        detailFormId: 'things-base-role-detail',
        titleField: 'name',
        description: 'Base.view.role.Role',
        itemsProp: 'items',
        resourceName: 'Role',
        routing: 'roles',
        totalProp: 'total',
        resourceUrl: 'roles',
        gridSaveUrl: 'roles/update_multiple',
        routingType: 'RESOURCE',
        name: 'Role',
        rank: 300,
        menuType: 'SCREEN',
        category: 'STANDARD',
        resourceType: 'ENTITY'
      },
      {
        template: 'things-system-user',
        idField: 'name',
        fixedColumns: 0,
        hiddenFlag: false,
        pagination: true,
        detailFormId: 'things-system-new-user',
        titleField: 'email',
        description: 'Base.view.user.User',
        itemsProp: 'items',
        resourceName: 'User',
        routing: 'users',
        totalProp: 'total',
        resourceUrl: 'users',
        gridSaveUrl: 'users/update_multiple',
        routingType: 'STATIC',
        name: 'User',
        rank: 200,
        menuType: 'SCREEN',
        category: 'STANDARD',
        resourceType: 'ENTITY'
      },
      {
        template: 'things-system-domain',
        idField: 'name',
        fixedColumns: 0,
        hiddenFlag: false,
        pagination: true,
        detailFormId: 'custom',
        titleField: 'name',
        description: 'Base.view.domain.DomainItem',
        itemsProp: 'items',
        resourceName: 'Domain',
        routing: 'domains',
        totalProp: 'total',
        resourceUrl: 'domains/search',
        gridSaveUrl: 'domains/update_multiple',
        routingType: 'STATIC',
        name: 'Domain',
        rank: 100,
        menuType: 'SCREEN',
        category: 'STANDARD',
        resourceType: 'ENTITY'
      },
      {
        idField: 'name',
        fixedColumns: 4,
        hiddenFlag: false,
        pagination: true,
        detailFormId: 'things-resource-form',
        itemsProp: 'items',
        resourceName: 'LoginHistory',
        routing: 'login_histories',
        totalProp: 'total',
        resourceUrl: 'login_histories',
        gridSaveUrl: 'login_histories/update_multiple',
        routingType: 'RESOURCE',
        name: 'LoginHistory',
        rank: 1700,
        menuType: 'SCREEN',
        category: 'STANDARD',
        resourceType: 'ENTITY'
      },
      {
        idField: 'name',
        fixedColumns: 4,
        hiddenFlag: false,
        pagination: true,
        detailFormId: 'things-resource-form',
        itemsProp: 'items',
        resourceName: 'UserHistory',
        routing: 'user_histories',
        totalProp: 'total',
        resourceUrl: 'user_histories',
        gridSaveUrl: 'user_histories/update_multiple',
        routingType: 'RESOURCE',
        name: 'UserHistory',
        rank: 1800,
        menuType: 'SCREEN',
        category: 'STANDARD',
        resourceType: 'ENTITY'
      },
      {
        idField: 'name',
        fixedColumns: 4,
        hiddenFlag: false,
        pagination: true,
        detailFormId: 'things-resource-form',
        itemsProp: 'items',
        resourceName: 'UserRoleHistory',
        routing: 'user_role_histories',
        totalProp: 'total',
        resourceUrl: 'user_role_histories',
        gridSaveUrl: 'user_role_histories/update_multiple',
        routingType: 'RESOURCE',
        name: 'UserRoleHistory',
        rank: 1900,
        menuType: 'SCREEN',
        category: 'STANDARD',
        resourceType: 'ENTITY'
      },
      {
        template: 'things-base-common-code',
        idField: 'name',
        fixedColumns: 0,
        hiddenFlag: false,
        pagination: true,
        detailFormId: 'things-base-code-detail',
        titleField: 'name',
        itemsProp: 'items',
        resourceName: 'Code',
        routing: 'common_codes',
        totalProp: 'total',
        resourceUrl: 'common_codes',
        gridSaveUrl: 'common_codes/update_multiple',
        routingType: 'STATIC',
        name: 'Code',
        rank: 600,
        menuType: 'SCREEN',
        category: 'STANDARD',
        resourceType: 'ENTITY'
      }
    ]
  },
  {
    fixedColumns: 0,
    hiddenFlag: false,
    pagination: false,
    name: 'Developer',
    rank: 11000,
    menuType: 'MENU',
    category: 'STANDARD',
    childrens: [
      {
        idField: 'name',
        fixedColumns: 4,
        hiddenFlag: false,
        pagination: true,
        detailFormId: 'things-resource-form',
        itemsProp: 'items',
        resourceName: 'PermitUrl',
        routing: 'permit_urls',
        totalProp: 'total',
        resourceUrl: 'permit_urls',
        gridSaveUrl: 'permit_urls/update_multiple',
        routingType: 'RESOURCE',
        name: 'PermitUrl',
        rank: 1900,
        menuType: 'SCREEN',
        category: 'STANDARD',
        resourceType: 'ENTITY'
      },
      {
        template: 'things-system-data-src',
        idField: 'name',
        fixedColumns: 4,
        hiddenFlag: false,
        pagination: true,
        detailFormId: 'things-resource-form',
        titleField: 'name',
        itemsProp: 'items',
        resourceName: 'DataSrc',
        routing: 'data_srcs',
        totalProp: 'total',
        resourceUrl: 'data_srcs',
        gridSaveUrl: 'data_srcs/update_multiple',
        routingType: 'STATIC',
        name: 'DataSrc',
        rank: 1700,
        menuType: 'SCREEN',
        category: 'STANDARD',
        resourceType: 'ENTITY'
      },
      {
        idField: 'name',
        fixedColumns: 4,
        hiddenFlag: false,
        pagination: true,
        detailFormId: 'things-base-entity-detail',
        titleField: 'name',
        description: 'Base.view.entity.Entity',
        itemsProp: 'items',
        resourceName: 'Entity',
        routing: 'entities',
        totalProp: 'total',
        resourceUrl: 'entities',
        gridSaveUrl: 'entities/update_multiple',
        routingType: 'RESOURCE',
        name: 'Entity',
        rank: 100,
        menuType: 'SCREEN',
        category: 'STANDARD',
        resourceType: 'ENTITY'
      }
    ]
  }
]
